In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [5]:
df=pd.read_csv(r"E:\Jupyter projects\Datasets\Life Expectancy Data.csv")
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [6]:
df.info

<bound method DataFrame.info of           Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0
1     Afghanistan  2014  Developing              59.9            271.0
2     Afghanistan  2013  Developing              59.9            268.0
3     Afghanistan  2012  Developing              59.5            272.0
4     Afghanistan  2011  Developing              59.2            275.0
...           ...   ...         ...               ...              ...
2933     Zimbabwe  2004  Developing              44.3            723.0
2934     Zimbabwe  2003  Developing              44.5            715.0
2935     Zimbabwe  2002  Developing              44.8             73.0
2936     Zimbabwe  2001  Developing              45.3            686.0
2937     Zimbabwe  2000  Developing              46.0            665.0

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154
1                64     0.01               73.523582         62.0       492
2                66     0.01               73.219243         64.0       430
3                69     0.01               78.184215         67.0      2787
4                71     0.01                7.097109         68.0      3013
...             ...      ...                     ...          ...       ...
2933             27     4.36                0.000000         68.0        31
2934             26     4.06                0.000000          7.0       998
2935             25     4.43                0.000000         73.0       304
2936             25     1.72                0.000000         76.0       529
2937             24     1.68                0.000000         79.0      1483

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
0     ...    6.0               8.16         65.0        0.1  584.259210
1     ...   58.0               8.18         62.0        0.1  612.696514
2     ...   62.0               8.13         64.0        0.1  631.744976
3     ...   67.0               8.52         67.0        0.1  669.959000
4     ...   68.0               7.87         68.0        0.1   63.537231
...   ...    ...                ...          ...        ...         ...
2933  ...   67.0               7.13         65.0       33.6  454.366654
2934  ...    7.0               6.52         68.0       36.7  453.351155
2935  ...   73.0               6.53         71.0       39.8   57.348340
2936  ...   76.0               6.16         75.0       42.1  548.587312
2937  ...   78.0               7.10         78.0       43.5  547.358878

      Population   thinness  1-19 years   thinness 5-9 years  \
0     33736494.0                   17.2                 17.3
1       327582.0                   17.5                 17.5
2     31731688.0                   17.7                 17.7
3      3696958.0                   17.9                 18.0
4      2978599.0                   18.2                 18.2
...          ...                    ...                  ...
2933  12777511.0                    9.4                  9.4
2934  12633897.0                    9.8                  9.9
2935    125525.0                    1.2                  1.3
2936  12366165.0                    1.6                  1.7
2937  12222251.0                   11.0                 11.2

      Income composition of resources  Schooling
0                               0.479       10.1
1                               0.476       10.0
2                               0.470        9.9
3                               0.463        9.8
4                               0.454        9.5
...                               ...        ...
2933                            0.407        9.2
2934                            0.418        9.5
2935                            0.427       10.0
2936                            0.427        9.8
2937                            0.434        9.8

[2938 rows x 22 columns]>

In [7]:
df.describe

<bound method NDFrame.describe of           Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0
1     Afghanistan  2014  Developing              59.9            271.0
2     Afghanistan  2013  Developing              59.9            268.0
3     Afghanistan  2012  Developing              59.5            272.0
4     Afghanistan  2011  Developing              59.2            275.0
...           ...   ...         ...               ...              ...
2933     Zimbabwe  2004  Developing              44.3            723.0
2934     Zimbabwe  2003  Developing              44.5            715.0
2935     Zimbabwe  2002  Developing              44.8             73.0
2936     Zimbabwe  2001  Developing              45.3            686.0
2937     Zimbabwe  2000  Developing              46.0            665.0

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154
1                64     0.01               73.523582         62.0       492
2                66     0.01               73.219243         64.0       430
3                69     0.01               78.184215         67.0      2787
4                71     0.01                7.097109         68.0      3013
...             ...      ...                     ...          ...       ...
2933             27     4.36                0.000000         68.0        31
2934             26     4.06                0.000000          7.0       998
2935             25     4.43                0.000000         73.0       304
2936             25     1.72                0.000000         76.0       529
2937             24     1.68                0.000000         79.0      1483

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
0     ...    6.0               8.16         65.0        0.1  584.259210
1     ...   58.0               8.18         62.0        0.1  612.696514
2     ...   62.0               8.13         64.0        0.1  631.744976
3     ...   67.0               8.52         67.0        0.1  669.959000
4     ...   68.0               7.87         68.0        0.1   63.537231
...   ...    ...                ...          ...        ...         ...
2933  ...   67.0               7.13         65.0       33.6  454.366654
2934  ...    7.0               6.52         68.0       36.7  453.351155
2935  ...   73.0               6.53         71.0       39.8   57.348340
2936  ...   76.0               6.16         75.0       42.1  548.587312
2937  ...   78.0               7.10         78.0       43.5  547.358878

      Population   thinness  1-19 years   thinness 5-9 years  \
0     33736494.0                   17.2                 17.3
1       327582.0                   17.5                 17.5
2     31731688.0                   17.7                 17.7
3      3696958.0                   17.9                 18.0
4      2978599.0                   18.2                 18.2
...          ...                    ...                  ...
2933  12777511.0                    9.4                  9.4
2934  12633897.0                    9.8                  9.9
2935    125525.0                    1.2                  1.3
2936  12366165.0                    1.6                  1.7
2937  12222251.0                   11.0                 11.2

      Income composition of resources  Schooling
0                               0.479       10.1
1                               0.476       10.0
2                               0.470        9.9
3                               0.463        9.8
4                               0.454        9.5
...                               ...        ...
2933                            0.407        9.2
2934                            0.418        9.5
2935                            0.427       10.0
2936                            0.427        9.8
2937                            0.434        9.8

[2938 rows x 22 columns]>

In [8]:
india = df[df['Country'].str.strip()=='India'].sort_values('Year')
india[['Year', 'infant deaths','Adult Mortality']].head(15)

      Year  infant deaths  Adult Mortality
1201  2000           1800            224.0
1200  2001           1800            222.0
1199  2002           1700            219.0
1198  2003           1700            216.0
1197  2004           1600            214.0
1196  2005           1500            211.0
1195  2006           1500             28.0
1194  2007           1400             26.0
1193  2008           1300             23.0
1192  2009           1300              2.0
1191  2010           1200            196.0
1190  2011           1100            193.0
1189  2012           1100             19.0
1188  2013           1000            187.0
1187  2014            957            184.0

In [9]:
india[['Year', 'infant deaths','Adult Mortality']].describe()

              Year  infant deaths  Adult Mortality
count    16.000000      16.000000        16.000000
mean   2007.500000    1366.687500       146.562500
std       4.760952     303.160402        89.558151
min    2000.000000     910.000000         2.000000
25%    2003.750000    1100.000000        27.500000
50%    2007.500000    1350.000000       190.000000
75%    2011.250000    1625.000000       214.500000
max    2015.000000    1800.000000       224.000000

In [10]:
x_year = india['Year'].values
y_infant_deaths = india['infant deaths'].values
plt.scatter(x_year, y_infant_deaths,color='red')
plt.show()

AttributeError: module 'matplotlib' has no attribute 'scatter'

In [ ]:
x_year = x_year.reshape(-1,1)
x_year

In [ ]:
model = LinearRegression().fit(x_year,y_infant_deaths)

In [ ]:
prediction = model.predict(x_year)

In [ ]:
plt.scatter(x_year,y_infant_deaths,color = 'red')
plt.plot(x_year,prediction,color='green')
plt.show()

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(x_year,y_infant_deaths,train_size=7, test_size=.3)
print(f"x_train shape = {x_train.shape}")
print(f"y_train shape = {y_train.shape}")
print(f"x_test shape = {x_test.shape}")
print(f"y_test shape = {y_test.shape}")

In [ ]:
plt.scatter(x_train,y_train,color='green')
plt.xlabel('Years')
plt.ylabel('Infant deaths')
plt.title('Training data')
plt.show()

In [ ]:
model = LinearRegression()
model.fit(x_train,y_train)
print(f"Train accuracy for Dataset {model.score(x_train,y_train)*100,2}%")
print(f"Test accuracy for Dataset {model.score(x_test,y_test)*100,2}%")

In [ ]:
rus = df[df['Country'].str.strip()=='Russian Federation'].sort_values('Year')
rus[['Year','infant deaths','Adult Mortality']].head(15)

In [ ]:
rus[['Year','infant deaths','Adult Mortality']].describe()

In [ ]:
x_year = rus['Year'].values
y_infant_deaths = rus['infant deaths'].values
plt.scatter(x_year, y_infant_deaths,color='red')
plt.show()

In [ ]:
y_infant_deaths

In [ ]:
x_year = x_year.reshape(-1,1)
x_year

In [ ]:
model = LinearRegression().fit(x_year,y_infant_deaths)

In [ ]:
prediction = model.predict(x_year)

In [ ]:
plt.scatter(x_year, y_infant_deaths,color='red')
plt.plot(x_year,prediction, color='green')
plt.show()

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(x_year,y_infant_deaths,train_size=7, test_size=.3)
print(f"x_train shape = {x_train.shape}")
print(f"y_train shape = {y_train.shape}")
print(f"x_test shape = {x_test.shape}")
print(f"y_test shape = {y_test.shape}")

In [ ]:
plt.scatter(x_train,y_train,color='green')
plt.xlabel('Years')
plt.ylabel('Infant deaths')
plt.title('Training data')
plt.show()

In [ ]:
plt.scatter(x_train,y_train,color='red')
plt.xlabel('Years')
plt.ylabel('Infant deaths')
plt.title('Training data')
plt.show()

In [ ]:
model = LinearRegression()
model.fit(x_train,y_train)
print(f"Train accuracy for Dataset {model.score(x_train,y_train)*100,2}%")
print(f"Test accuracy for Dataset {model.score(x_test,y_test)*100,2}%")